# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Markdown specs
markdown: kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               karthikselva
tagline:             '#SoftwareEngineer #SalesforceDeveloper #RubyonRails #Music'
description:         'Karthik Selvakumar Bhuvaneswaran is a Software Engineer working on Saas(RoR) and PaaS(Salesforce.com) applications. He likes experimenting anything from hardware to software technology and also talking about physics to philosophy. He beleives on day starts at night and requires nothing more than Music, a cup of cofee and a fully charged laptop.'
url:                 https://karthikselva.github.io
baseurl:             ''

# About/contact
author:
  name:              karthikselva
  url:               https://twitter.com/karthikselva
  email:             karthikselvakumar7@gmail.com

# Custom vars
version:             0.0.3

# Gems
gems: ['jekyll/scholar']

# Scholar
scholar:
  style: modern-language-association
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  relative: "/ed/bibliography.html"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

